export enum ActionStep {
  SELECT_ATTACK_TARGET = 'SELECT_ATTACK_TARGET',
  SELECT_POWER_DOWN_TARGET = 'SELECT_POWER_DOWN_TARGET',
  SELECT_DESTROY_TARGET = 'SELECT_DESTROY_TARGET',
  SELECT_SOUL_CANON_COST = 'SELECT_SOUL_CANON_COST',
  SELECT_SOUL_CANON_TARGET = 'SELECT_SOUL_CANON_TARGET',
  SELECT_SPEED_DRAGON_BIRD_COST = 'SELECT_SPEED_DRAGON_BIRD_COST',
  SELECT_SPEED_DRAGON_BIRD_TARGET = 'SELECT_SPEED_DRAGON_BIRD_TARGET',
  SELECT_FRESH_FISH_COST = 'SELECT_FRESH_FISH_COST',
  SELECT_HEDRON_COST = 'SELECT_HEDRON_COST',
  COMPLETED = 'COMPLETED',
}
