export enum ActionStep {
  SELECT_ATTACK_TARGET = 'SELECT_ATTACK_TARGET',
  SELECT_POWER_DOWN_TARGET = 'SELECT_POWER_DOWN_TARGET',
  SELECT_SOUL_CANON_COST = 'SELECT_SOUL_CANON_COST',
  SELECT_SOUL_CANON_TARGET = 'SELECT_SOUL_CANON_TARGET',
  COMPLETED = 'COMPLETED',
}
