import { ActionStep } from './action-steps';

export const InitialActionStep = {
  START_DRAW_TIME: ActionStep.COMPLETED,
  START_ENERGY_TIME: ActionStep.COMPLETED,
  START_PUT_TIME: ActionStep.COMPLETED,
  START_SOMETHING_TIME: ActionStep.COMPLETED,
  START_BATTLE_TIME: ActionStep.COMPLETED,
  START_END_TIME: ActionStep.COMPLETED,
  FINISH_END_TIME: ActionStep.COMPLETED,
  PUT_SOUL: ActionStep.COMPLETED,
  CHANGE_BATTLE_POSITION: ActionStep.COMPLETED,
  USE_SOUL_CANON: ActionStep.SELECT_SOUL_CANON_COST,
  SUMMON_MONSTER: ActionStep.COMPLETED,
  ATTACK: ActionStep.SELECT_ATTACK_TARGET,
  USE_SOUL_BARRIER: ActionStep.COMPLETED, // TODO: to be changed
  EFFECT_RUTERUTE_DRAW: ActionStep.COMPLETED,
  EFFECT_FRESH_FISH_DRAW: ActionStep.SELECT_FRESH_FISH_COST,
  EFFECT_NATSUKASHINORUDE_POWER_DOWN: ActionStep.SELECT_POWER_DOWN_TARGET,
  EFFECT_EMERALD_ENERGY_INCREASE: ActionStep.COMPLETED,
  EFFECT_SUPERNEWVOLTS_DESTROY_MONSTER: ActionStep.SELECT_DESTROY_TARGET,
  EFFECT_SPEED_DRAGON_BIRD_CHANGE_POSITION:
    ActionStep.SELECT_SPEED_DRAGON_BIRD_COST,
  SELECT_AS_HAMONTAKI_TARGET: ActionStep.COMPLETED,
  USE_HEDRON: ActionStep.SELECT_HEDRON_COST,
  SELECT_AS_HEDRON_TARGET: ActionStep.COMPLETED,
};
