# docker compose -f deploy/docker-compose.yml pull
# docker compose -f deploy/docker-compose.yml --env-file deploy/.env up -d

version: "2.4"

services:
  mysql:
    image: mysql:8
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --innodb_lock_wait_timeout=10
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${DB_PASSWORD}"]
      interval: 5s
      timeout: 10s
      retries: 10

# TODO: migrate用のサービス追加

  server:
    image: solt9029/soulmonsters-server:latest
    ports:
      - "8201:3100"
    environment:
      DB_TYPE: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_SYNCHRONIZE: "false"
      CORS_ORIGIN: ${CORS_ORIGIN}
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      FIREBASE_CLIENT_EMAIL: ${FIREBASE_CLIENT_EMAIL}
      FIREBASE_DATABASE_URL: ${FIREBASE_DATABASE_URL}
      FIREBASE_PRIVATE_KEY: ${FIREBASE_PRIVATE_KEY}
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

  client:
    image: solt9029/soulmonsters-client:latest
    environment:
      NGINX_BASIC_AUTH_USER: ${NGINX_BASIC_AUTH_USER}
      NGINX_BASIC_AUTH_PASS: ${NGINX_BASIC_AUTH_PASS}
    ports:
      - "8200:80"
    restart: unless-stopped

volumes:
  mysql_data:
