name: Server Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'server/**'
      - '.github/workflows/server-test.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'server/**'
      - '.github/workflows/server-test.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./server

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: soulmonsters_test
        ports:
          - 3307:3306

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.14.0'
        cache: 'yarn'
        cache-dependency-path: server/yarn.lock

    - name: Install dependencies
      run: yarn install --frozen-lockfile
    
    - name: Run database migrations
      run: yarn db:migrate
      env:
        NODE_ENV: test
        DB_HOST: localhost
        DB_PORT: 3307
        DB_USERNAME: root
        DB_PASSWORD: root
        DB_DATABASE: soulmonsters_test
        DB_TYPE: mysql

    - name: Run tests
      run: yarn test
      env:
        NODE_ENV: test
        DB_HOST: localhost
        DB_PORT: 3307
        DB_USERNAME: root
        DB_PASSWORD: root
        DB_DATABASE: soulmonsters_test
        DB_TYPE: mysql
